### ISSUE TITLE
[Feature Request] Change the size of the image in the reader

### ISSUE THREAD

**Issue by AFKoide** [Suwayomi/Tachidesk-WebUI#183]
## What feature should be added to Tachidesk?
Tachiyomi's app for mobile allow to change how the page is displayed on the screen : adjust based on the height/length, dynamic, original image size (etc.). I think Tachidesk just need the first one : height/length.

##  Why/Project's Benefit
Some pages are simply too big for the Tachidesk. In these cases, you need to scroll to read everything, or zoom out using the browser.

###  Proposition of Code
I tried a few things in CSS, and manage to set the image based on it's height :
* I disable `min-width`. 
* I set `height`'s value at `100vh`. 
I only tested with vertical's manga pages.

I also tried modifying the other parameters, and found that setting `max-width` at `100vh` zoom out the page, less than if height had this value, but still.

Someone on [Tachidesk-Server] told me to post it here (sorry if it feels a bit duplicate)

**Comment by Masterbaiter** [comment]
The scaling is not very good especially in single page mode, for vertical pages, you almost always have to scroll down to see the whole page, because the page is scaled to fit the width instead of height. 
This is a major problem for mobile and tablets for the most part, because I think very few people would use single page mode on desktop.

**Comment by schroda** [comment]
duplicate to https://github.com/Suwayomi/Tachidesk-WebUI/issues/134
