### ISSUE TITLE
[Question] Close Button at Reader Settings

### ISSUE THREAD

**Issue by ntbm** [Suwayomi/Tachidesk-WebUI#58]
The Close Icon in the Reader Settings onClick calls `history.back()` which is the previous chapter if you've read a while. 
Is this intended behaviour? For me the expected behavior would be either closing the Settings Nav(but there's already a button for it) or going back to the manga detail page.

**Comment by AriaMoradi** [comment]
It used to work like that, but with the new back button being added, its changed and now broken?

**Comment by AriaMoradi** [comment]
as a fix, the back button could pop any path urls that have `/chapter/` in them? until it reaches something else
or pop and then redirect to manga page?

**Comment by abhijeetChawla** [comment]
When you go to the prev/next chapter in the reader view, there no new entry made to history stack, instead it replaces current entry on History.
So,
If history is 
Manga -> chapter 1.
Then going to the next chapter will change the history to 
Manga -> Chapter 2.
So using history.goBack() is all we need to go back since nothing is added to the stack after the initial chapter entry

**Comment by ntbm** [comment]
For the Chapter Selection in the Nav that's true, but not for the Chapters which were loaded while in endless mode.
See:
https://github.com/Suwayomi/Tachidesk-WebUI/blob/master/src/screens/Reader.tsx#L161
https://github.com/Suwayomi/Tachidesk-WebUI/blob/master/src/screens/Reader.tsx#L167

**Comment by AriaMoradi** [comment]
Are we good now?

**Comment by ntbm** [comment]
Yes
